from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ISLAND_SEASON_ENTRY = Button(area={'cn': (0, 0, 56, 54), 'en': (0, 0, 56, 54), 'jp': (0, 0, 56, 54), 'tw': (0, 0, 56, 54)}, color={'cn': (221, 220, 218), 'en': (221, 220, 218), 'jp': (221, 220, 218), 'tw': (221, 220, 218)}, button={'cn': (0, 0, 56, 54), 'en': (0, 0, 56, 54), 'jp': (0, 0, 56, 54), 'tw': (0, 0, 56, 54)}, file={'cn': './assets/cn/island_season_plan/ISLAND_SEASON_ENTRY.png', 'en': './assets/cn/island_season_plan/ISLAND_SEASON_ENTRY.png', 'jp': './assets/cn/island_season_plan/ISLAND_SEASON_ENTRY.png', 'tw': './assets/cn/island_season_plan/ISLAND_SEASON_ENTRY.png'})
